apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
  labels:
    app: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
      containers:
      - name: explorer
        image: hyperledger/explorer:1.1.6
        #command: ["sh" , "-c" , "/fabric/config/explorer/app/run.sh"]
        #command: [ "sh", "-c" ]
        #args: ["cp /fabric/config/explorer/app/config.json /opt/explorer/app/platform/fabric/"]
        env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        #- name: DISCOVERY_AS_LOCALHOST
        #  value: false
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles