--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: chaincode-marbles-org
  labels:
    app: chaincode-marbles-org
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-marbles-org
