---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: onlock-chaincode-org1
  labels:
    app: onlock-chaincode-org1
spec:
  selector:
    matchLabels:
      app: onlock-chaincode-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlock-chaincode-org1
    spec:
      hostname: onlock-chaincode-org1
      containers:
        - image: 880382163732.dkr.ecr.us-east-1.amazonaws.com/onlock-blockchain-chaincode:12
          name: onlock-chaincode-org1
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "onlock:5d7c4ba10ea873cf3d43a4f63d652c9a6721b9ce29e44edb6e8037395a67b385"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:9999"            
            - name: TZ
              value: "America/Sao_Paulo"
          ports:
            - containerPort: 9999
