--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: onlock-chaincode-org2
  labels:
    app: onlock-chaincode-org2
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9999
      targetPort: 9999
  selector:
    app: onlock-chaincode-org2
